version: '2'
services:
  db:
    image: camptocamp/postgis:9.6
    ports:
      - "5432:5432"
    restart: always
  web:
    build: .
    command: bundle exec rails s -e production -p 3000 -b '0.0.0.0'
    volumes:
      - .:/computercore
    ports:
      - "80:3000"
    depends_on:
      - db
    environment:
      - SECRET_KEY_BASE="78096685bc2f8167a9b057e00460746897cb6c11d403a31b5ceaed9c33eee83d6fc09e2b931c4e2a62b89b6a3791dde05ce2cc2b461a3b2817d861ce714e78f9"
    restart: always
