default: &default
  adapter: postgis
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: computer_core_development
  user: computer_core_development
  password: password

test:
  <<: *default
  database: computer_core_test
  user: computer_core_test
  password: password

production:
  <<: *default
  database: computer_core
  user: computer_core
  password: password
